// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: extern/sector-memory/proto/rpc.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SectorMemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageID      string `protobuf:"bytes,1,opt,name=storageID,proto3" json:"storageID,omitempty"`
	ActorID        uint64 `protobuf:"varint,2,opt,name=actorID,proto3" json:"actorID,omitempty"`
	SectorNumber   uint64 `protobuf:"varint,3,opt,name=sectorNumber,proto3" json:"sectorNumber,omitempty"`
	SectorFileType int64  `protobuf:"varint,4,opt,name=sectorFileType,proto3" json:"sectorFileType,omitempty"`
	Primary        bool   `protobuf:"varint,5,opt,name=primary,proto3" json:"primary,omitempty"`
}

func (x *SectorMemRequest) Reset() {
	*x = SectorMemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extern_sector_memory_proto_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SectorMemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectorMemRequest) ProtoMessage() {}

func (x *SectorMemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extern_sector_memory_proto_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectorMemRequest.ProtoReflect.Descriptor instead.
func (*SectorMemRequest) Descriptor() ([]byte, []int) {
	return file_extern_sector_memory_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SectorMemRequest) GetStorageID() string {
	if x != nil {
		return x.StorageID
	}
	return ""
}

func (x *SectorMemRequest) GetActorID() uint64 {
	if x != nil {
		return x.ActorID
	}
	return 0
}

func (x *SectorMemRequest) GetSectorNumber() uint64 {
	if x != nil {
		return x.SectorNumber
	}
	return 0
}

func (x *SectorMemRequest) GetSectorFileType() int64 {
	if x != nil {
		return x.SectorFileType
	}
	return 0
}

func (x *SectorMemRequest) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

type SectorMemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer uint64 `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *SectorMemResponse) Reset() {
	*x = SectorMemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extern_sector_memory_proto_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SectorMemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectorMemResponse) ProtoMessage() {}

func (x *SectorMemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extern_sector_memory_proto_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectorMemResponse.ProtoReflect.Descriptor instead.
func (*SectorMemResponse) Descriptor() ([]byte, []int) {
	return file_extern_sector_memory_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SectorMemResponse) GetAnswer() uint64 {
	if x != nil {
		return x.Answer
	}
	return 0
}

var File_extern_sector_memory_proto_rpc_proto protoreflect.FileDescriptor

var file_extern_sector_memory_proto_rpc_proto_rawDesc = []byte{
	0x0a, 0x24, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x2f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01,
	0x0a, 0x10, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26,
	0x0a, 0x0e, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x22, 0x2b, 0x0a, 0x11, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x9e, 0x01,
	0x0a, 0x04, 0x47, 0x72, 0x70, 0x63, 0x12, 0x48, 0x0a, 0x13, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72,
	0x65, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4c, 0x0a, 0x17, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x53,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extern_sector_memory_proto_rpc_proto_rawDescOnce sync.Once
	file_extern_sector_memory_proto_rpc_proto_rawDescData = file_extern_sector_memory_proto_rpc_proto_rawDesc
)

func file_extern_sector_memory_proto_rpc_proto_rawDescGZIP() []byte {
	file_extern_sector_memory_proto_rpc_proto_rawDescOnce.Do(func() {
		file_extern_sector_memory_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_extern_sector_memory_proto_rpc_proto_rawDescData)
	})
	return file_extern_sector_memory_proto_rpc_proto_rawDescData
}

var file_extern_sector_memory_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extern_sector_memory_proto_rpc_proto_goTypes = []interface{}{
	(*SectorMemRequest)(nil),  // 0: proto.SectorMemRequest
	(*SectorMemResponse)(nil), // 1: proto.SectorMemResponse
}
var file_extern_sector_memory_proto_rpc_proto_depIdxs = []int32{
	0, // 0: proto.Grpc.DeclareSectorMemory:input_type -> proto.SectorMemRequest
	0, // 1: proto.Grpc.StorageDropSectorMemory:input_type -> proto.SectorMemRequest
	1, // 2: proto.Grpc.DeclareSectorMemory:output_type -> proto.SectorMemResponse
	1, // 3: proto.Grpc.StorageDropSectorMemory:output_type -> proto.SectorMemResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extern_sector_memory_proto_rpc_proto_init() }
func file_extern_sector_memory_proto_rpc_proto_init() {
	if File_extern_sector_memory_proto_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extern_sector_memory_proto_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SectorMemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extern_sector_memory_proto_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SectorMemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extern_sector_memory_proto_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extern_sector_memory_proto_rpc_proto_goTypes,
		DependencyIndexes: file_extern_sector_memory_proto_rpc_proto_depIdxs,
		MessageInfos:      file_extern_sector_memory_proto_rpc_proto_msgTypes,
	}.Build()
	File_extern_sector_memory_proto_rpc_proto = out.File
	file_extern_sector_memory_proto_rpc_proto_rawDesc = nil
	file_extern_sector_memory_proto_rpc_proto_goTypes = nil
	file_extern_sector_memory_proto_rpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcClient interface {
	DeclareSectorMemory(ctx context.Context, in *SectorMemRequest, opts ...grpc.CallOption) (*SectorMemResponse, error)
	StorageDropSectorMemory(ctx context.Context, in *SectorMemRequest, opts ...grpc.CallOption) (*SectorMemResponse, error)
}

type grpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcClient(cc grpc.ClientConnInterface) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) DeclareSectorMemory(ctx context.Context, in *SectorMemRequest, opts ...grpc.CallOption) (*SectorMemResponse, error) {
	out := new(SectorMemResponse)
	err := c.cc.Invoke(ctx, "/proto.Grpc/DeclareSectorMemory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) StorageDropSectorMemory(ctx context.Context, in *SectorMemRequest, opts ...grpc.CallOption) (*SectorMemResponse, error) {
	out := new(SectorMemResponse)
	err := c.cc.Invoke(ctx, "/proto.Grpc/StorageDropSectorMemory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServer is the server API for Grpc service.
type GrpcServer interface {
	DeclareSectorMemory(context.Context, *SectorMemRequest) (*SectorMemResponse, error)
	StorageDropSectorMemory(context.Context, *SectorMemRequest) (*SectorMemResponse, error)
}

// UnimplementedGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcServer struct {
}

func (*UnimplementedGrpcServer) DeclareSectorMemory(context.Context, *SectorMemRequest) (*SectorMemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclareSectorMemory not implemented")
}
func (*UnimplementedGrpcServer) StorageDropSectorMemory(context.Context, *SectorMemRequest) (*SectorMemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageDropSectorMemory not implemented")
}

func RegisterGrpcServer(s *grpc.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_DeclareSectorMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SectorMemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).DeclareSectorMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Grpc/DeclareSectorMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).DeclareSectorMemory(ctx, req.(*SectorMemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_StorageDropSectorMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SectorMemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).StorageDropSectorMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Grpc/StorageDropSectorMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).StorageDropSectorMemory(ctx, req.(*SectorMemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeclareSectorMemory",
			Handler:    _Grpc_DeclareSectorMemory_Handler,
		},
		{
			MethodName: "StorageDropSectorMemory",
			Handler:    _Grpc_StorageDropSectorMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc.proto",
}
